{
  "openapi": "3.1.0",
  "info": {
    "title": "Create Security Account",
    "version": "1.0",
    "description": ""
  },
  "servers": [
    {
      "url": "http://localhost:8722"
    }
  ],
  "paths": {
    "/client-services/security-account/": {
      "post": {
        "summary": "Create Security Account",
        "operationId": "post-client-services-security-account",
        "responses": {
          "200": {
            "$ref": "#/components/responses/SecurityAccountResponse"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "InstId",
            "required": true
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/PortfolioBean"
        }
      }
    }
  },
  "components": {
    "responses": {
      "Unauthorized": {
        "description": "Unauthorized response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "STS": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "nvjfbsg606qrp"
                  },
                  "default": 401,
                  "description": "Status"
                },
                "error": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "tetl3lgl5git1"
                  },
                  "default": "Unauthorized",
                  "description": "Error Code"
                },
                "path": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "45rd4yx2ujzfk"
                  }
                }
              }
            }
          }
        }
      },
      "SecurityAccountResponse": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "oneOf": [
                {
                  "properties": {
                    "SEC_ACC_NUM": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "2lq4ksc5smw3k"
                      },
                      "description": "Security Account Number"
                    },
                    "MSG_ID": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "p2dtffeiprsqk"
                      },
                      "description": "Message Id"
                    },
                    "STS": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "1fb3ag3vh9mgm"
                      },
                      "description": "Status"
                    },
                    "ERR": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "vzpmrte2bprqa"
                      },
                      "description": "Error"
                    }
                  }
                },
                {
                  "x-stoplight": {
                    "id": "eqcsbxfum03vl"
                  },
                  "properties": {
                    "MSG_ID": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "qs2b893j072e8"
                      },
                      "description": "Message Id"
                    },
                    "STS": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "qwlnx90r0yh7r"
                      },
                      "description": "Status"
                    },
                    "ERR": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "6mqucv30bvmox"
                      },
                      "description": "Error Code"
                    }
                  }
                }
              ],
              "type": "object"
            },
            "examples": {
              "Success Response": {
                "value": {
                  "SEC_ACC_NUM": "S001133109",
                  "MSG_ID": "94556",
                  "STS": 1,
                  "ERR": 0
                }
              },
              "Unsuccess Response 1": {
                "value": {
                  "MSG_ID": "94455",
                  "STS": 0,
                  "ERR": 4001,
                  "RSN": "Invalid Mubasher Account Number"
                }
              },
              "Unsuccess Response 2": {
                "value": {
                  "MSG_ID": "94455",
                  "STS": 0,
                  "ERR": 4002,
                  "RSN": "Invalid Cash Account Number"
                }
              },
              "Unsuccess Response 3": {
                "value": {
                  "MSG_ID": "94455",
                  "STS": 0,
                  "ERR": 4003,
                  "RSN": "Error persisting portfolio account bean"
                }
              },
              "Unsuccess Response 4": {
                "value": {
                  "MSG_ID": "94455",
                  "STS": 0,
                  "ERR": 4004,
                  "RSN": "Error Creating the Portfolio Account"
                }
              }
            }
          }
        }
      }
    },
    "requestBodies": {
      "PortfolioBean": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "MSG_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "4nhjj6isk88gn"
                  },
                  "description": "Message Id"
                },
                "CUS_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "hpx8ezwvalajd"
                  },
                  "description": "Customer Id"
                },
                "CSH_ACC": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "lqrhertkg26ms"
                  },
                  "description": "Cash Account"
                },
                "BROKER_REFERENCE": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "o1wjcuee5d7iv"
                  }
                }
              },
              "required": [
                "MSG_ID",
                "CUS_ID",
                "CSH_ACC"
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "MSG_ID": "94556",
                  "CUS_ID": "992209991",
                  "BROKER_PTF_REF": "888",
                  "CSH_ACC": "C004088038"
                }
              }
            }
          }
        }
      }
    }
  }
}