{
  "openapi": "3.1.0",
  "info": {
    "title": "Get Order Information by OrderId",
    "version": "1.0",
    "description": ""
  },
  "servers": [
    {
      "url": "http://localhost:8722"
    }
  ],
  "paths": {
    "/client-services/all-orders-by-order-id": {
      "post": {
        "summary": "Get Order Information by OrderId",
        "operationId": "post-client-services-all-orders-by-order-id",
        "responses": {
          "200": {
            "$ref": "#/components/responses/OrderDataByOrderIdResponse"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "InstId",
            "required": true
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/OrderInfoByOrderIdRequestBean"
        }
      }
    }
  },
  "components": {
    "responses": {
      "Unauthorized": {
        "description": "Unauthorized response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "STS": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "nvjfbsg606qrp"
                  },
                  "default": 401,
                  "description": "Status"
                },
                "error": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "tetl3lgl5git1"
                  },
                  "default": "Unauthorized",
                  "description": "Error Code"
                },
                "path": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "45rd4yx2ujzfk"
                  }
                }
              }
            }
          }
        }
      },
      "OrderDataByOrderIdResponse": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "MSG_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "ftlcus1vzd18g"
                  },
                  "description": "Message Id"
                },
                "STS": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "1ohnj612q7p0s"
                  },
                  "description": "Status"
                },
                "ERR": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "k3askxrvw1elz"
                  },
                  "description": "Error Code"
                },
                "ORDS": {
                  "type": "array",
                  "x-stoplight": {
                    "id": "sgga20e8s9h3m"
                  },
                  "description": "Orders",
                  "items": {
                    "x-stoplight": {
                      "id": "k7934phr0zugi"
                    },
                    "type": "object",
                    "properties": {
                      "CUS_ID": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "zna8vqug7c279"
                        },
                        "description": "Customer Id"
                      },
                      "SEC_ACC_NUM": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "26e00qhlovnkc"
                        },
                        "description": "Security Account Number"
                      },
                      "CUSTODIAN": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "6yfb5in6nrh5p"
                        },
                        "description": "Custodian"
                      },
                      "ORD_STS": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "j86mgvku1rwmc"
                        },
                        "description": "Order Status"
                      },
                      "ORD_CHNL": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "0oqiasvmv8407"
                        },
                        "description": "Order Channel"
                      },
                      "SYM": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "7bfs0hsaahrok"
                        },
                        "description": "Symbol"
                      },
                      "EXG": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "64dmwfzbke572"
                        },
                        "description": "Exchange"
                      },
                      "ORD_TYPE": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "21ux3e9uysqse"
                        },
                        "description": "Order Type"
                      },
                      "SIDE": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "pb6b5br1xtunv"
                        }
                      },
                      "ORD_QTY": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "zonh76h3vy7an"
                        },
                        "description": "Order Quantity"
                      },
                      "TME_IN_FORCE": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "l1hixevkzistt"
                        }
                      },
                      "MIN_QTY": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "a0v2m7utwva63"
                        },
                        "description": "Minimum Quantity"
                      },
                      "MAX_FLOOR": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "iswneunb8q22p"
                        }
                      },
                      "ORD_ID": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "6zv78fouixsjy"
                        },
                        "description": "Order Id"
                      },
                      "EXEC_ID": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "ywesokdbql39y"
                        },
                        "description": "Execution Id"
                      },
                      "COMM": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "noybeaut27556"
                        },
                        "description": "Commission"
                      },
                      "CRTD_DATE": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "eatu4ai8bwqfh"
                        },
                        "description": "Created Date"
                      },
                      "FIX_MSG_TYP": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "72dgtepc2z1sd"
                        },
                        "description": "Fix Message Type"
                      },
                      "PRICE": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "xc9wt4hy2o261"
                        }
                      },
                      "TRD_ACC_NUM": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "ibxbdxno0e1qo"
                        },
                        "description": "Trade Account Number"
                      },
                      "EXP_TME": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "rhbesh0b2daq4"
                        },
                        "description": "Expiry Time"
                      },
                      "EXG_COMM": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "95nrfnutosf2o"
                        },
                        "description": "Exchange Commission"
                      },
                      "RMT_CL_ORD_ID": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "2t6ht7d2fpono"
                        },
                        "description": "Remote CL Order Id"
                      },
                      "RMT_ORG_CL_ORD_ID": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "qrncbu11p0vvx"
                        },
                        "description": "Remote Original CL Order Id"
                      },
                      "RMT_ORD_NUM": {
                        "type": "integer",
                        "x-stoplight": {
                          "id": "xti5pa961eoxf"
                        },
                        "description": "Remote Order Number"
                      },
                      "ISS_STL_RTE": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "ojuzu3djfc326"
                        },
                        "description": "Issue Settle Rate"
                      },
                      "AS_OF_DTE": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "81bkej83c89ps"
                        },
                        "description": "As Of Date"
                      },
                      "EXT_REF_NO": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "xnbgw8o0fvf2f"
                        },
                        "description": "External Reference Number"
                      },
                      "CURR": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "g5f5y4mgnec03"
                        },
                        "description": "Currency"
                      },
                      "STP_PRC": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "q770gkqtp5kvr"
                        },
                        "description": "Stop Price"
                      },
                      "LST_UPD_DTE": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "n0roj6unhbxh4"
                        },
                        "description": "Last Updated Date"
                      },
                      "ORD_RJCT_RSN": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "l3edwtokchidh"
                        },
                        "description": "Order Reject Reason"
                      },
                      " DLR_NME": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "ixe5t59wprm9y"
                        },
                        "description": "Dealer Name"
                      },
                      "CHANNEL": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "71f163kegzumw"
                        },
                        "description": "Channel"
                      },
                      "ORD_VAL": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "ataa21ik8ck4x"
                        },
                        "description": "Order Value"
                      },
                      "NET_SETTLE": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "siz839vy4r6wo"
                        }
                      },
                      "COST_COMM": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "366b887e26na1"
                        },
                        "description": "Cost Commission"
                      },
                      "ORD_FESS": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "e7hko6qgu3ywl"
                        },
                        "description": "Order Fess"
                      },
                      "BRK_COMM": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "6bkuttim5rch8"
                        },
                        "description": "Bank Commission"
                      },
                      "VAT_AMOUNT": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "njxiz4rq187ev"
                        }
                      },
                      "EXT_CSH_ACC_NUM": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "vohfeot0j2c61"
                        },
                        "description": "External Cash Account Number"
                      },
                      "PTF_NME": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "3qd2l679magcf"
                        },
                        "description": "Portfolio Name"
                      },
                      "ISIN_CODE": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "m5jz327b05t2w"
                        }
                      },
                      "AVG_PRCE": {
                        "type": "number",
                        "x-stoplight": {
                          "id": "cn360ikwcc9kz"
                        },
                        "description": "Average Price"
                      },
                      "EXT_SEC_NUM": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "3s094aqk6lgc2"
                        },
                        "description": "External Security Number"
                      },
                      "TRD_CURR": {
                        "type": "string",
                        "x-stoplight": {
                          "id": "ybya45zzx6dgc"
                        },
                        "description": "Trade Currency"
                      }
                    }
                  }
                }
              }
            },
            "examples": {
              "Succsess Response ": {
                "value": {
                  "MSG_ID": "1234",
                  "ORDS": [
                    {
                      "CUS_ID": "530364911",
                      "SEC_ACC_NUM": "P001131264",
                      "CUSTODIAN": "",
                      "ORD_STS": "2",
                      "ORD_CHNL": 4,
                      "SYM": "AAPL",
                      "EXG": "NSDQ",
                      "ORD_TYPE": "Limit",
                      "SIDE": 2,
                      "ORD_QTY": 0.4125,
                      "TME_IN_FORCE": 0,
                      "MIN_QTY": 0,
                      "MAX_FLOOR": 0,
                      "ORD_ID": "23U142000134",
                      "EXEC_ID": "23U142000134",
                      "COMM": 2.5241,
                      "CRTD_DATE": "09/14/2023 12:26:13",
                      "FIX_MSG_TYP": "D",
                      "PRICE": 174.7,
                      "TRD_ACC_NUM": "11111",
                      "EXP_TME": "09/14/2023 23:59:59",
                      "EXG_COMM": 2.52,
                      "RMT_CL_ORD_ID": 0,
                      "RMT_ORG_CL_ORD_ID": -1,
                      "RMT_ORD_NUM": 10873360,
                      "ISS_STL_RTE": 1,
                      "AS_OF_DTE": "09/14/2023 00:00:00",
                      "EXT_REF_NO": "",
                      "CURR": "USD",
                      "STP_PRC": 0,
                      "LST_UPD_DTE": "09/14/2023 00:00:00",
                      "ORD_RJCT_RSN": "",
                      "DLR_NME": "GROOT",
                      "CHANNEL": "Manual",
                      "ORD_VAL": 72.06724,
                      "NET_SETTLE": 69.5431,
                      "COST_COMM": 2.5241,
                      "ORD_FESS": 0.02,
                      "BRK_COMM": 0,
                      "VAT_AMOUNT": 0,
                      "EXT_CSH_ACC_NUM": "",
                      "PTF_NME": "P001131264-USD",
                      "ISIN_CODE": "US0378331005",
                      "AVG_PRCE": 174.7,
                      "EXT_SEC_NUM": "",
                      "TRD_CURR": "USD"
                    }
                  ],
                  "STS": 1,
                  "ERR": 0
                }
              },
              "Unsuccess Response 1": {
                "value": {
                  "MSG_ID": "908778",
                  "STS": 0,
                  "ERR": 48001,
                  "RSN": "Invalid customer number parameters"
                }
              },
              "Unsuccess Response 2": {
                "value": {
                  "MSG_ID": "908778",
                  "STS": 0,
                  "ERR": 48002,
                  "RSN": "Invalid Order Id"
                }
              },
              "Unsuccess Response 3": {
                "value": {
                  "MSG_ID": "908778",
                  "STS": 0,
                  "ERR": 48003,
                  "RSN": "Invalid Customer Number"
                }
              },
              "Unsuccess Response 4": {
                "value": {
                  "MSG_ID": "908778",
                  "STS": 0,
                  "ERR": 47004,
                  "RSN": "Error in getting all order data"
                }
              },
              "Unsuccess Response 5": {
                "value": {
                  "MSG_ID": "908778",
                  "STS": 0,
                  "ERR": 48005,
                  "RSN": "Unmatched customer no, order id and institution id"
                }
              },
              "Unsuccess Response 6": {
                "value": {
                  "MSG_ID": "908778",
                  "STS": 0,
                  "ERR": 48006,
                  "RSN": "Error in parameters"
                }
              }
            }
          }
        }
      }
    },
    "requestBodies": {
      "OrderInfoByOrderIdRequestBean": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "MSG_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "8kkgplvigvz8v"
                  },
                  "description": "Message Id"
                },
                "CUS_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "vtntob0hpoaet"
                  },
                  "description": "Customer Id"
                },
                "ORD_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "6hmiuptd7dr7z"
                  },
                  "description": "Order Id"
                },
                "EXT_REF_NO": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "1avns176iuo7k"
                  },
                  "description": "External Reference Number"
                }
              },
              "required": [
                "MSG_ID",
                "CUS_ID",
                "ORD_ID"
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "MSG_ID": "94445333",
                  "CUS_ID": "ASI878953958",
                  "ORD_ID": "24G062000070"
                }
              }
            }
          }
        }
      }
    }
  }
}