{
  "openapi": "3.1.0",
  "info": {
    "title": "Reset Password",
    "version": "1.0",
    "description": ""
  },
  "servers": [
    {
      "url": "http://localhost:8722"
    }
  ],
  "paths": {
    "/client-services/reset-password": {
      "post": {
        "summary": "Reset Password",
        "operationId": "post-client-services-reset-password",
        "responses": {
          "200": {
            "$ref": "#/components/responses/ResetPwdResponse"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "InstId",
            "required": true
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/ResetPasswordRequestBean"
        }
      }
    }
  },
  "components": {
    "responses": {
      "Unauthorized": {
        "description": "Unauthorized response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "STS": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "nvjfbsg606qrp"
                  },
                  "default": 401,
                  "description": "Status"
                },
                "error": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "tetl3lgl5git1"
                  },
                  "default": "Unauthorized",
                  "description": "Error Code"
                },
                "path": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "45rd4yx2ujzfk"
                  }
                }
              }
            }
          }
        }
      },
      "ResetPwdResponse": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "MSG_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "40jyi8mmkmbp2"
                  }
                },
                "STS": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "58recgt5vnrgm"
                  }
                },
                "ERR": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "ajytcreo74fil"
                  }
                },
                "RSN": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "mv9ac7s2uxkkd"
                  }
                }
              }
            },
            "examples": {
              "Success Response": {
                "value": {
                  "MSG_ID": "1234",
                  "STS": 0,
                  "RSN": "Error in getting details about customer",
                  "ERR": 57004
                }
              },
              "Unsuccess Response 1": {
                "value": {
                  "MSG_ID": "1234",
                  "STS": 0,
                  "RSN": "password resetting process is failed : Invalid customer Number",
                  "ERR": 57001
                }
              },
              "Unsuccess Response 2": {
                "value": {
                  "MSG_ID": "1234",
                  "STS": 0,
                  "RSN": "Error in getting details about customer",
                  "ERR": 57002
                }
              },
              "Unsuccess Response 3": {
                "value": {
                  "MSG_ID": "1234",
                  "STS": 0,
                  "RSN": "Error in Hashing password",
                  "ERR": 57004
                }
              },
              "Unsuccess Response 4": {
                "value": {
                  "MSG_ID": "1234",
                  "STS": 0,
                  "RSN": "Password resetting process failed,Invalid customer Number",
                  "ERR": 57005
                }
              },
              "Unsuccess Response 5": {
                "value": {
                  "MSG_ID": "1234",
                  "STS": 0,
                  "RSN": "Password resetting process of  the customer is failed",
                  "ERR": 57006
                }
              }
            }
          }
        }
      }
    },
    "requestBodies": {
      "ResetPasswordRequestBean": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "MSG_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "2bgjuz3gj5rck"
                  }
                },
                "CUS_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "vkkhxbmo7ob65"
                  }
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "MSG_ID": "0915688",
                  "CUS_ID": "238076698"
                }
              }
            }
          }
        }
      }
    }
  }
}