{
  "openapi": "3.1.0",
  "info": {
    "title": "Withdrawal Request",
    "version": "1.0",
    "description": ""
  },
  "servers": [
    {
      "url": "http://localhost:8722"
    }
  ],
  "paths": {
    "/client-services/withdraw": {
      "post": {
        "summary": "Withdrawal Request",
        "operationId": "post-client-services-withdraw",
        "responses": {
          "200": {
            "$ref": "#/components/responses/CashWithdrawalResponse"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "InstId",
            "required": true
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/DepositRequestBean"
        }
      }
    }
  },
  "components": {
    "responses": {
      "Unauthorized": {
        "description": "Unauthorized response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "STS": {
                  "type": "integer",
                  "x-stoplight": {
                    "id": "nvjfbsg606qrp"
                  },
                  "default": 401,
                  "description": "Status"
                },
                "error": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "tetl3lgl5git1"
                  },
                  "default": "Unauthorized",
                  "description": "Error Code"
                },
                "path": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "45rd4yx2ujzfk"
                  }
                }
              }
            }
          }
        }
      },
      "CashWithdrawalResponse": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "oneOf": [
                {
                  "properties": {
                    "MSG_ID": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "j68fcivselqyh"
                      },
                      "description": "Message Id"
                    },
                    "CSH_LG_ID": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "2tx5os7xh26yt"
                      },
                      "description": "Cash Log Id"
                    },
                    "BAL": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "9kh7v7f0ex6wj"
                      },
                      "description": "Balance"
                    },
                    "TRANS_ID": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "7sfus3gqh8k83"
                      },
                      "description": "Transaction Id"
                    },
                    "STS": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "07mz16y80clts"
                      },
                      "description": "Status"
                    },
                    "ERR": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "hk8jlazun7z6p"
                      },
                      "description": "Error Code"
                    }
                  }
                },
                {
                  "x-stoplight": {
                    "id": "yuqcwgg4znkah"
                  },
                  "properties": {
                    "MSG_ID": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "ifdyn8ee2ho50"
                      },
                      "description": "Message Id"
                    },
                    "STS": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "60u0t6o6dk42v"
                      },
                      "description": "Status"
                    },
                    "ERR": {
                      "type": "integer",
                      "x-stoplight": {
                        "id": "z27rfi5zx4lmt"
                      },
                      "description": "Error Code"
                    },
                    "RSN": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "r0kj3jdy1bdkv"
                      },
                      "description": "Reason"
                    }
                  }
                }
              ],
              "type": "object"
            },
            "examples": {
              "Success Response": {
                "value": {
                  "CSH_LG_ID": "1707796559559",
                  "BAL": "900.0",
                  "TRANS_ID": "1707796559558",
                  "MSG_ID": "96002",
                  "STS": 1,
                  "ERR": 0
                }
              },
              "Unsuccess Response 1": {
                "value": {
                  "MSG_ID": "12345",
                  "STS": 0,
                  "ERR": 11001,
                  "RSN": "Invalid Mubasher Account Number"
                }
              },
              "Unsuccess Response 2": {
                "value": {
                  "MSG_ID": "12345",
                  "STS": 0,
                  "ERR": 11002,
                  "RSN": "Invalid Cash Account Number"
                }
              },
              "Unsuccess Response 3": {
                "value": {
                  "MSG_ID": "12345",
                  "STS": 0,
                  "ERR": 11003,
                  "RSN": "Invalid Broker Cash Account Reference"
                }
              },
              "Unsuccess Response 4": {
                "value": {
                  "MSG_ID": "12345",
                  "STS": 0,
                  "ERR": 11004,
                  "RSN": "Invalid Currency"
                }
              },
              "Unsuccess Response 5": {
                "value": {
                  "MSG_ID": "12345",
                  "STS": 0,
                  "ERR": 11005,
                  "RSN": "Invalid Deposit Amount"
                }
              },
              "Unsuccess Response 6": {
                "value": {
                  "MSG_ID": "12345",
                  "STS": 0,
                  "ERR": 11006,
                  "RSN": "System Error"
                }
              }
            }
          }
        }
      }
    },
    "requestBodies": {
      "DepositRequestBean": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "MSG_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "951ri4oakeebt"
                  },
                  "description": "Message Id"
                },
                "CUS_ID": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "hzd0vsk6bz3n5"
                  },
                  "description": "Customer Id"
                },
                "CSH_ACC": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "tkepjms2lgk6l"
                  },
                  "description": "Cash Account"
                },
                "BROKER_CASH_ACC_REF": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "vlln66t8wzizf"
                  },
                  "description": "Broker Cash Account Reference"
                },
                "CURR": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "2nupqv2fxyxml"
                  },
                  "description": "Currency"
                },
                "AMOUNT": {
                  "type": "number",
                  "x-stoplight": {
                    "id": "30i1qd3j2vql6"
                  },
                  "default": 0
                },
                "NARR": {
                  "type": "string",
                  "x-stoplight": {
                    "id": "znzq2habnqsyp"
                  },
                  "description": "Narration"
                }
              },
              "required": [
                "MSG_ID",
                "CUS_ID",
                "CSH_ACC",
                "BROKER_CASH_ACC_REF",
                "CURR",
                "AMOUNT"
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "MSG_ID": "99945",
                  "CUS_ID": "951248752",
                  "CSH_ACC": "C004088040",
                  "BROKER_CASH_ACC_REF": "193489991",
                  "CURR": "USD",
                  "AMOUNT": 1000
                }
              }
            }
          }
        }
      }
    }
  }
}